[package]
name = "random_dog"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { workspace = true }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
tokio = { version = "1.42.0", features = ["full"] }
